rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_url>\w+)/$', views.category, name='category'),
        url(r'^category/(?P<category_name_url>\w+)/add_page/$', views.add_page, name='add_page'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^restricted/$', views.restricted, name='restricted'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^search/$', views.search, name='search'),
        url(r'^profile/$', views.profile, name='profile'),
        url(r'^goto/$', views.track_url, name='track_url'),
        url(r'^like_category/$', views.like_category, name='like_category'),
        url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
        url(r'^auto_add_page/$', views.auto_add_page, name='auto_add_page'),
)

tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from rango import views
from django.contrib import admin
admin.autodiscover()
from django.conf import settings

urlpatterns = patterns('',
url(r'^rango/', include('rango.urls', namespace='rango')),
# Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns(
            'django.views.static',
            (r'media/(?P<path>.*)',
            'serve',
            {'document_root': settings.MEDIA_ROOT}), )

rango/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() -datetime.timedelta(days=1)

    def __unicode__(self):
        return self.title

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'





class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank = True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __unicode__(self):
        return self.user.username
    

rango/forms.py
from django import forms
from rango.models import Page, Category
#from django.utils import timezone
from rango.models import UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Please Enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    
    class Meta:
        model = Category



class PageForm(forms.ModelForm):
    title= forms.CharField(max_length=128, help_text='Please enter the title of the page.')
    url= forms.URLField(max_length=200, help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    #pub_date = forms.DateTimeField(widget=forms.HiddenInput())

    class Meta:
        model = Page
        fields = ('title', 'url', 'views')

    #def clean(self):
        #cleaned_data = self.cleaned_data
        #url = cleaned_data.get('url')

        #if url and (not url.startswith('http://') or not url.startswith('https://')):
#or not url.startswith('https://')):
            #url = 'http://' + url
            #cleaned_data['url'] = url
        #return cleaned_data



class UserForm(forms.ModelForm):
    username = forms.CharField(help_text='Please enter a username.')
    email = forms.EmailField(help_text='Please enter your email.')
    password = forms.CharField(widget=forms.PasswordInput(),help_text="Please enter a password.")
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(help_text='Please enter your website.', required=False)
    picture = forms.ImageField(help_text='Select a profile image to upload.', required=False)
    class Meta:
        model = UserProfile
        fields = ('website', 'picture') 

rango/views.py
from django.shortcuts import render

from django.http import HttpResponse

from django.template import RequestContext
from django.shortcuts import render, render_to_response, get_object_or_404

from rango.models import Category, Page

from rango.forms import CategoryForm, PageForm
from django.utils import timezone

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime

from rango.bing_search import run_query

from django.contrib.auth.models import User#, UserProfile
from rango.models import UserProfile
from django.shortcuts import redirect

#from django.http import Http404



def get_cat_list():
    cat = Category.objects.all()
    for category in cat:
        category.url = category.name.replace(' ', '_')
    return cat





def index(request): 
    #request.session.set_test_cookie()#just a test
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    

    for category in category_list:
        category.url = category.name.replace(' ', '_')
    context_dict = {'categories': category_list, 'pages': page_list}

    if request.session.get('last_visit_date'):
        last_visit_date = request.session.get('last_visit_date')
        num_of_visits = request.session.get('num_of_visits', 0)

        if (datetime.now() - datetime.strptime(last_visit_date[:-7], "%Y-%m-%d %H:%M:%S")).days > 0:
            request.session['num_of_visits'] = num_of_visits + 1
            request.session['last_visit_date'] = str(datetime.now())
    else:
        request.session['num_of_visits'] = 1
        request.session['last_visit_date'] = str(datetime.now())
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/index.html', context_dict)
    




def about(request):
    context_dict = {'visits': 0}
    if request.session.get('num_of_visits'):
        context_dict['visits'] = request.session['num_of_visits']    
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/about.html', context_dict)

def category(request, category_name_url):
    context = RequestContext(request)
    category_name = category_name_url.replace('_', ' ')
    context_dict = {'category_name':category_name}


    try:
        category = Category.objects.get(name=category_name)
        
    #category = get_object_or_404(Category, name=category_name)        

        pages = Page.objects.filter(category=category).order_by('-views')

        context_dict['pages'] = pages
        context_dict['category'] = category
        context_dict['category_name_url'] = category_name_url
    
    except Category.DoesNotExist:

        pass
        #raise Http404
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render_to_response('rango/category.html', context_dict, context)    
        

@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)#What's commit?
            #return index(request)
            return HttpResponseRedirect(reverse('rango:index'))
        else:
            print form.errors
    else:
        form = CategoryForm()
    context_dict = {'form': form}
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/add_category.html', context_dict)


def encode_url(url):
    return url.replace(' ', '_')

def decode_url(url):
    return url.replace('_', ' ')

@login_required
def add_page(request, category_name_url):
    category_name = decode_url(category_name_url)
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid(): 
            page = form.save(commit=False)
            cat = Category.objects.get(name=category_name)
            page.category = cat
            page.views = 0
            page.pub_date = timezone.now()
            page.save()
            #return category(request, category_name_url)
            return HttpResponseRedirect(reverse('rango:category', args=(category_name_url,)))
        else:
            print form.errors
            #print form 
    else:
        form = PageForm()
    
    context_dict = {'category_name_url':category_name_url, 'category_name':category_name, 'form':form}
    #DONT EVER FORGET RETURN!!!!!!!!!!!!!
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/add_page.html', context_dict)




def register(request):
    #if request.session.test_cookie_worked():
        #print '>>>> TEST COOKIE WORKED!'
        #request.session.delete_test_cookie()
            #just a test^
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            
            user = user_form.save()
            #user = user_form
            
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)#This is unnecessary as well since pic/url is not required
            profile.user = user#Do we need this??
            #I guess yes, because this 'user' is new one, and needs to referenced to newly created profile...
           

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True

        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context_dict = {'user_form': user_form}
    context_dict['profile_form'] = profile_form
    context_dict['registered'] = registered
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/register.html', context_dict)


def user_login(request):
    disabled_account = False
    error_message= False
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

            # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))

            else:
                disabled_account = True
        
        else:
            print 'Invalid login details: {0}, {1}'.format(username, password)#<- print out in the TERMINAL!!!
            #return HttpResponse('Invalid login details supplied.')
            error_message = True
    #else:
    context_dict = {'error_message':error_message}
    context_dict['disabled_account'] = disabled_account
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/login.html', context_dict) 




@login_required
def restricted(request):
    context_dict = dict()
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/restricted.html', context_dict) 

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))
    


def search(request):
    result_list =[]
    search_query = ''
    if request.method =='POST':
        print 'Hello'+request.POST['query']+'World'
        query = request.POST['query'].strip()

        if query:
            print 'query!'
            result_list = run_query(query)
            search_query = query
    context_dict = {'result_list':result_list}
    context_dict['search_query'] = search_query
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    return render(request, 'rango/search.html', context_dict)




@login_required
def profile(request):
    context_dict = {}
    cat_list = get_cat_list()        
    context_dict['cat_list'] = cat_list
    u = User.objects.get(username=request.user)
    try:
        up = UserProfile.objects.get(user=u)
    except:
        up = None
    context_dict['user'] = u
    context_dict['userprofile'] = up
    return render(request, 'rango/profile.html', context_dict)


def track_url(request):
    #context_dict = {}
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                url = page.url
            except:
                pass
    return redirect(url)


@login_required
def like_category(request):
    #context = RequestContext(request)
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']

    likes = 0
    
    if cat_id:
        category = Category.objects.get(id=int(cat_id))
        if category:
            likes = category.likes + 1
            category.likes = likes
            category.save()

    return HttpResponse(likes+1)    




def get_category_list(max_results=0, starts_with=''):
   
    cat_list = []

    if starts_with:
        cat_list = Category.objects.filter(name__startswith=starts_with)
    else:
        cat_list = Category.objects.all()
        
    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]

    for cat in cat_list:

templates/rango/about.html
{% extends 'rango/base.html' %}

{% load static %}

{% block title %}About{% endblock %}

{% block body_block %}

<div class="hero-unit">
        <h1><em>Rango</em> says...</h1>
        Here is <strong>About Page!</strong><br />
        <p style='color:brown; font-family:Courier;'>You have visited {{ visits }} times!</p>
        
        <img src='{% static 'forkit.gif' %}' alt='Picture of Github'/>
</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title %}Add a New Category!{% endblock %}
{% block body_block %}
<div class='hero-unit'>
        <h1>Add a Category</h1>
      
        <br />
    <div class=container>
        <form class='span6' id='category_form' method='post' action='/rango/add_category/'>   
        {% csrf_token %}


        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}
        {% endfor %}
        
        <button class='btn btn-primary' type='submit' name='submit'>Create Category</button>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title %}Add a New Page!{% endblock %}

{% block body_block %}
<div class='hero-unit'>

        {% if category_name %}
        <h1>Add a Page</h1>
        <br>
        <div class='container'>
            <form class='span6' id='page_form' method='post' action="{% url 'rango:add_page' category_name_url %}">
            {% csrf_token %}
        
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.help_text }}<br>
                {{ field}}
                {% if field.errors %}
                {{ field.errors }}
                {% else %}
                <br><br>
                {% endif %}
         {% endfor %}
                <button class='btn btn-primary' type='submit' name='submit'>Create Page</button>
            </form>
    {% else %}
        <em>The category <strong>{{ category_name }}</strong> doesn't exist. Create a new category from <a href='{% url 'rango:index' %}'>Index Page</a></em>
    {% endif %}
</div>
</div>
{% endblock %}  

templates/rango/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>

        <link href='{% static 'css/bootstrap-fluid-adj.css' %}' rel='stylesheet'>
        <link href='{% static 'css/bootstrap.min.css' %}' rel='stylesheet' media='screen'>
        <link href='{% static 'css/bootstrap-responsive.css' %}' rel='stylesheet'>






        <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
    </head>
    <body>

<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url 'rango:index' %}">Rango</a>
          <div class="nav-collapse collapse">
            <ul class="nav pull-right">
            {% if user.is_authenticated %}
            <li class="navbar-text">Welcome, {{user.username}}</li>
            <li><a href='{% url 'rango:logout' %}'>Logout</a></li>
            {% else %}
            <li><a href='{% url 'rango:register' %}'>Register</a></li>
            <li><a href='{% url 'rango:login' %}'>Login</a></li>
            {% endif %}
            </ul>
            <ul class="nav">
              {% if user.is_authenticated %}
              <li><a href='{% url 'rango:profile' %}'>Profile</a></li>
              <li class="active"><a href="{% url 'rango:add_category' %}">Add Category</a></li>
              <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
              {% endif %}
              <li><a href="{% url 'rango:about' %}">About</a></li>
              <li><a href='{% url 'rango:search' %}'>Search</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>





<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                   
                        <li class="nav-header">Find a Category</li>
                        <form>
                        <label></label>
                        <li><input class="search-query span10" type="text" name="suggestion" value="" id="suggestion" /></li>
                        </form>
                </ul>

        {% if cat_list %}
                 
                         {% include 'rango/category_list.html' %}
                 
         {% endif %}



            </div>
            <!--/.well -->

        </div>
 <div class="span9">


        <div>
        {% block body_block %}{% endblock %}
        </div>
</div>
 </div>

<hr>

<footer>
        <div class='container'>
        <p>&copy; Rango 2013</p>
        </div>  
      </footer>

         


        

        

<script src='{% static 'js/jquery-2.0.3.min.js' %}'></script>
<script src='{% static 'js/bootstrap.min.js' %}'></script>
<script src='{% static 'js/rango-ajax.js' %}'></script>


    </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{%block title %}{{ category_name }}{% endblock %}

{%block body_block %}
    <div class='hero-unit'>
        <h1>{{ category_name }}</h1>
        <br>
        {% if category %}
            {% if pages %}
            <ul>
                {% for page in pages %}
                <li><a href='/rango/goto/?page_id={{page.id}}'>{{ page.title }}</a></li>
                    {% if page.views > 1 %}
                        - ({{page.views}}views)
                    {% elif page.views == 1 %}
                        - ( 1 view)
                    {% endif %}
                {% endfor %}
            </ul>
            
            {% else %}
                <strong>No pages currently in category.</strong>
            {% endif %}
            {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category_name_url %}">Add a New Page!</a>
            {% endif %}
        {% else %}
            The specific category {{ category_name }} does not exist!<br> 
            {% if user.is_authenticated %}
    <em>Create a new category from <strong><a href='{% url 'rango:add_category' %}'>Here</a></strong></em>
            {% endif %}
        {% endif %}

<p>

<b id='like_count'>{{ category.likes }}</b> people like this category

{% if user.is_authenticated %}
    <button id='likes' data-catid='{{category.id}}' class='btn btn-mini btn-primary' type='button'>Like</button>
</p>

{% else %}

<a href='{% url 'rango:register' %}'>Register to Like {{ category_name }}</a>
</p>
{% endif %}





</div>
{% endblock %}
        
        

templates/rango/category_list.html
<div id="cats">
<ul class="nav nav-list">
         {% if cat_list %}
                {% for cat in cat_list %}
                 <li><a href="{% url 'rango:category' cat.url %}">{{ cat.name }}</a></li>
                {% endfor %}
         {% else %}
                <li>No categories at present.</li>
         {% endif %}
        </ul>

</div>

templates/rango/index.html
{% extends 'rango/base.html' %}



{% block body_block %}
<div class='hero-unit'>
        {% if user.is_authenticated %}
        <h1>Rango says.. Hello, {{ user.username }}!</h1>
        {% else %}
        <h1>Rango says...hello world!</h1>
        {% endif %}
</div>
<div class='row-fluid'>
    <div class='span6'>
        <h2>Top 5 Categories</h2>
        {% if categories %}
            <ul>
                {% for category in categories %}
                <li><a href='{% url 'rango:category' category.url %}'>{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present</strong>
        {% endif %}
   </div><!-- span -->
    <div class='span6'>

    <h2>Top 5 Most Viewed Pages</h2>
        {% if pages %}
            <ol>
                {% for page in pages %}
                <li><a href={{page.url}}>{{ page.title }}</a></li>
                {% endfor %}
            </ol>
        {% else %}
            <strong> The pages are not viewed enough!</strong>
        {% endif %}

</div>  
       </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}

{% block title %}Login{% endblock %}

{% block body_block %}
<div class='hero-unit'>
        
        <h1>Login to Rango</h1>
        <div class='container'>
        <form class='form-signin span6' id='login_form' method='post' action='{% url 'rango:login' %}'>
        <h2 class='form-signin-heading'>Please sign in</h2>
       
 {% csrf_token %}

        {% if error_message %}
        <p style='color:red; font-family:serif'><strong>The username or password you entered is incorrect!<strong></p>
        {% elif disabled_account %}
        <p style='color:red; font-family:serif'><strong>Your Rango account is currently disabled; we can't log you in!</strong></p>
        {% else %}
         <p>Login from Here!</p>
        {% endif %}

        Username: <input type='text' class='input-block-level' placeholder='Username' name='username' value='' size='50'/>
        <br />
        Password: <input type='password' class ='input-block-level' placeholder='password' name='password' value='' size='50' />
        <br />
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
    

        
        </form>
    </div>
</div>
{% endblock %}

templates/rango/page_list.html
{% if pages %}
    <ul>
        {% for page in pages %}
        <li>
            <a href="/rango/goto/?page_id={{page.id}}">{{page.title}}</a>
            {% if page.views > 1 %}
                - ({{ page.views }} views)
            {% elif page.views == 1 %}
                - ({{ page.views }} view)
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong><br/>
{% endif %}

templates/rango/profile.html
{% extends 'rango/base.html' %}

{% block title %}Profile of {{ user.username }}{% endblock %}

{% block body_block %}
<div class='hero-unit'>
<h1>Profile of {{ user.username }}</h1>
<br>
        <div class='container'>
<ul>
<li>Name: {{ user.username }}</li>
<li>Email: {{ user.email }}</li>
{% if userprofile.website %}
<li>Website: {{userprofile.website}}</li>
    {% if userprofile.picture %}
<li>Picture: {{userprofile.picture}}</li>
    {% endif %}
{% endif %}
</div>
</div>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% block title %}Register{% endblock %}
{% block body_block %}
<div class='hero-unit'>
        <h1>Register with Rango</h1>
<br>
<div class='container'>
        {% if registered %}
        Rango says: <strong>Thank you for registering!</strong>
        <a href='{% url 'rango:login' %}'>When you are ready to Rango</a><br />
        
        {% else %}

        
        <form class='form-signin span8' id='user_form' method='post' action='{% url 'rango:register' %}' enctype='multipart/form-data'>
        <h2 class='form-signin-heading'>Rango says: <strong>Register here!</strong></h2>
        {% csrf_token %}
       {% for field in user_form.visible_fields %}
        
        {{field.help_text}}<br>
        {{field}}
        {{field.errors}}<br>
        {% endfor %}

        {% for field in profile_form.visible_fields %}
        {{field.errors}}
        {{field.help_text}}<br>
        {{field}}<br>
        {% endfor %}
        <br>
        <button class='btn btn-primary' type='submit' name='submit'>Register</button>

        </form>

        
        {% endif %}
</div>
</div>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block title %}Restricted Page{% endblock %}

{% block body_block %}
<div class='hero-unit'>
<p style='font-family:Garamond; color:brown;'>Since You're logged in, you can see this text.</p>

{% endblock %}
</div>

templates/rango/search.html
{% extends 'rango/base.html' %}



{% block title %}Search{% endblock %}

{% block body_block %}

<div class='hero-unit'>
    <h1>Search with Rango</h1>
    <br>
    <div class='container-fluid'>
        <form class='form-signin span8' id='user_form' method='post' action='{% url 'rango:search' %}'>
        {% csrf_token %}
        <input type='text' size='50' name='query' value='{{ search_query }}' id='query' />
        <input class='btn btn-primary' type='submit' name='submit'  value='search' />
        <br>
        </form>

        {% if result_list %}
        <div style='clear:both;'>
            <ol>
            {% for result in result_list %}
            <li>
                <strong><a href='{{ result.link }}'>{{result.title}}</a></strong>
{% if user.is_authenticated %}
    <button id='add' data-catid='{{category.id}}' data-title='{{ result.title }}' data-url='{{ result.link }}'  class='rango-add btn btn-mini btn-primary' type='button'>Add</button>
{% endif %}

<br>
                <em>{{ result.summary}}</em>
            </li>
            {% endfor %}
            </ol>
            </div>
            {% endif %}
    </div>
<div>

{% endblock %} 